### ISSUE TITLE
Repeat character after tab-complete / expansion

### ISSUE THREAD

**Issue by gabrielfreiberg** [jeremyFreeAgent/oh-my-zsh-powerline-theme#41]
![repeat_character](https://cloud.githubusercontent.com/assets/1455224/7836214/a035b9f2-044c-11e5-8fe1-18d589c74663.jpg)

After a tab-complete, a repeat character shows up, and other weird behavior happens at the text prompt.  I've tried suggestions online saying to add the following to the top of my .zshrc:

```
export LC_ALL="en_US.UTF-8"
export LANG="en_US.UTF-8"
export TERM="xterm-256color"
```

Do you have any fixes for this?  I'm on OSX using iTerm2, also using the powerline-fonts.

**Comment by mixedCase** [comment]
Can reproduce. Doesn't happen with earlier versions.

**Comment by mixedCase** [comment]
In the meantime remove the line ZLE_RPROMPT_INDENT=0 from the file powerline.zsh-theme

This fixes it for me.

**Comment by gabrielfreiberg** [comment]
Wow, that fixes it for me too!  Nicely done @mixedCase .. how'd you figure it out?

**Comment by mixedCase** [comment]
There's only one commit in 2015, the previous one being from 2013.

It's the first env var in the commit and it's used by shell, so... first thing I tried, hahaha.

**Comment by piyueh** [comment]
I can also reproduce this. And commenting out `ZLE_RPROMPT_INDENT=0` also resolved the problem for me.

**Comment by Spy-Seth** [comment]
I have the problem on my new computer. And removing `ZLE_RPROMPT_INDENT=0` also resolve the problem. :scream: 

Thanks @mixedCase!

**Comment by idoo** [comment]
@mixedCase thank you!

**Comment by idoo** [comment]
https://github.com/jeremyFreeAgent/oh-my-zsh-powerline-theme/pull/45

**Comment by jeremyFreeAgent** [comment]
After reading some blogpost, we are not the only one to have that issue. Currently, we should keep the white space at the right.
